// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_contact from "./routes/api/contact.ts";
import * as $api_data from "./routes/api/data.ts";
import * as $index from "./routes/index.tsx";
import * as $Card from "./islands/Card.tsx";
import * as $Contact from "./islands/Contact.tsx";
import * as $ErrorBoundary from "./islands/ErrorBoundary.tsx";
import * as $Experience from "./islands/Experience.tsx";
import * as $Hero from "./islands/Hero.tsx";
import * as $Navbar from "./islands/Navbar.tsx";
import * as $ParticleBackground from "./islands/ParticleBackground.tsx";
import * as $Projects from "./islands/Projects.tsx";
import * as $ThemeToggle from "./islands/ThemeToggle.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/contact.ts": $api_contact,
    "./routes/api/data.ts": $api_data,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Card.tsx": $Card,
    "./islands/Contact.tsx": $Contact,
    "./islands/ErrorBoundary.tsx": $ErrorBoundary,
    "./islands/Experience.tsx": $Experience,
    "./islands/Hero.tsx": $Hero,
    "./islands/Navbar.tsx": $Navbar,
    "./islands/ParticleBackground.tsx": $ParticleBackground,
    "./islands/Projects.tsx": $Projects,
    "./islands/ThemeToggle.tsx": $ThemeToggle,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
